[build]
	publish = "dist/public"
	command = "pnpm build"

[dev]
	publish = "dist/public"
	port = 8888

[[redirects]]
	from = "/api/*"
	to = "/.netlify/functions/server"
	status = 200
	force = true

[[redirects]]
 from = "/*"
 to = "/index.html"
 status = 200